[package]
name = "merkle_bench"
version = "0.1.0"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.2"
ark-ec = "0.2"
ark-groth16 = "0.2"
ark-ed-on-bls12-381 = "0.2"
ark-relations = "0.2"
ark-r1cs-std = "0.2"
ark-std = "0.2"

[dependencies.ark-crypto-primitives]
git = "https://github.com/rozbb/crypto-primitives.git"
branch = "merkle-changes"
features = ["r1cs"]

[features]
default = ["asm", "parallel"]
parallel = [
    "ark-groth16/parallel",
    "ark-std/parallel",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-r1cs-std/parallel"
]
asm = ["ark-ff/asm"]
