[package]
name = "merkle_bench"
version = "0.1.0"
authors = ["Michael Rosenberg <michael@mrosenberg.pub>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives.git", branch = "main", commit = "6be6062" }
ark-ff = "0.2"
ark-ec = "0.2"
ark-std = "0.2"
ark-ed-on-bls12-381 = "0.2"
